// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// soft_cpp
arma::mat soft_cpp(const arma::mat& X, const arma::mat& u, int q, int n);
RcppExport SEXP _bdsvd_soft_cpp(SEXP XSEXP, SEXP uSEXP, SEXP qSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type u(uSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(soft_cpp(X, u, q, n));
    return rcpp_result_gen;
END_RCPP
}
// calc_one_sparse_v_cpp
Rcpp::List calc_one_sparse_v_cpp(const arma::mat& X, arma::vec v, arma::vec u, int n, int maxit, double tol);
RcppExport SEXP _bdsvd_calc_one_sparse_v_cpp(SEXP XSEXP, SEXP vSEXP, SEXP uSEXP, SEXP nSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type u(uSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_one_sparse_v_cpp(X, v, u, n, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// calc_BIC
Rcpp::NumericVector calc_BIC(const arma::mat& X, arma::vec u, arma::vec v, const arma::vec& dof_grid, int maxit, int anp, int n, int p);
RcppExport SEXP _bdsvd_calc_BIC(SEXP XSEXP, SEXP uSEXP, SEXP vSEXP, SEXP dof_gridSEXP, SEXP maxitSEXP, SEXP anpSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type dof_grid(dof_gridSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< int >::type anp(anpSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_BIC(X, u, v, dof_grid, maxit, anp, n, p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bdsvd_soft_cpp", (DL_FUNC) &_bdsvd_soft_cpp, 4},
    {"_bdsvd_calc_one_sparse_v_cpp", (DL_FUNC) &_bdsvd_calc_one_sparse_v_cpp, 6},
    {"_bdsvd_calc_BIC", (DL_FUNC) &_bdsvd_calc_BIC, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_bdsvd(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
