# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soft_cpp <- function(X, u, q, n) {
    .Call(`_bdsvd_soft_cpp`, X, u, q, n)
}

calc_one_sparse_v_cpp <- function(X, v, u, n, maxit = 500L, tol = 0.001) {
    .Call(`_bdsvd_calc_one_sparse_v_cpp`, X, v, u, n, maxit, tol)
}

calc_BIC <- function(X, u, v, dof_grid, maxit, anp, n, p) {
    .Call(`_bdsvd_calc_BIC`, X, u, v, dof_grid, maxit, anp, n, p)
}

